In [29]:
%matplotlib inline
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [30]:
wine_df = pd.read_csv('wine.xls', names = ["Cultivator", "Alchol", "Malic_Acid", "Ash", "Alcalinity_of_Ash", "Magnesium", "Total_phenols", "Falvanoids", "Nonflavanoid_phenols", "Proanthocyanins", "Color_intensity", "Hue", "OD280", "Proline"])

In [31]:
wine_df.columns

Index(['Cultivator', 'Alchol', 'Malic_Acid', 'Ash', 'Alcalinity_of_Ash',
       'Magnesium', 'Total_phenols', 'Falvanoids', 'Nonflavanoid_phenols',
       'Proanthocyanins', 'Color_intensity', 'Hue', 'OD280', 'Proline'],
      dtype='object')

In [32]:
wine_df.shape

(178, 14)

In [33]:
wine_df.describe().transpose()

count        mean         std     min       25%  \
Cultivator            178.0    1.938202    0.775035    1.00    1.0000   
Alchol                178.0   13.000618    0.811827   11.03   12.3625   
Malic_Acid            178.0    2.336348    1.117146    0.74    1.6025   
Ash                   178.0    2.366517    0.274344    1.36    2.2100   
Alcalinity_of_Ash     178.0   19.494944    3.339564   10.60   17.2000   
Magnesium             178.0   99.741573   14.282484   70.00   88.0000   
Total_phenols         178.0    2.295112    0.625851    0.98    1.7425   
Falvanoids            178.0    2.029270    0.998859    0.34    1.2050   
Nonflavanoid_phenols  178.0    0.361854    0.124453    0.13    0.2700   
Proanthocyanins       178.0    1.590899    0.572359    0.41    1.2500   
Color_intensity       178.0    5.058090    2.318286    1.28    3.2200   
Hue                   178.0    0.957449    0.228572    0.48    0.7825   
OD280                 178.0    2.611685    0.709990    1.27    1.9375   
Proline               178.0  746.893258  314.907474  278.00  500.5000   

                          50%       75%      max  
Cultivator              2.000    3.0000     3.00  
Alchol                 13.050   13.6775    14.83  
Malic_Acid              1.865    3.0825     5.80  
Ash                     2.360    2.5575     3.23  
Alcalinity_of_Ash      19.500   21.5000    30.00  
Magnesium              98.000  107.0000   162.00  
Total_phenols           2.355    2.8000     3.88  
Falvanoids              2.135    2.8750     5.08  
Nonflavanoid_phenols    0.340    0.4375     0.66  
Proanthocyanins         1.555    1.9500     3.58  
Color_intensity         4.690    6.2000    13.00  
Hue                     0.965    1.1200     1.71  
OD280                   2.780    3.1700     4.00  
Proline               673.500  985.0000  1680.00

In [34]:
wine_df.head(10)  #let us look at the raw data. As is evident, there are lot of missing values 

Cultivator  Alchol  Malic_Acid   Ash  Alcalinity_of_Ash  Magnesium  \
0           1   14.23        1.71  2.43               15.6        127   
1           1   13.20        1.78  2.14               11.2        100   
2           1   13.16        2.36  2.67               18.6        101   
3           1   14.37        1.95  2.50               16.8        113   
4           1   13.24        2.59  2.87               21.0        118   
5           1   14.20        1.76  2.45               15.2        112   
6           1   14.39        1.87  2.45               14.6         96   
7           1   14.06        2.15  2.61               17.6        121   
8           1   14.83        1.64  2.17               14.0         97   
9           1   13.86        1.35  2.27               16.0         98   

   Total_phenols  Falvanoids  Nonflavanoid_phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   
5           3.27        3.39                  0.34             1.97   
6           2.50        2.52                  0.30             1.98   
7           2.60        2.51                  0.31             1.25   
8           2.80        2.98                  0.29             1.98   
9           2.98        3.15                  0.22             1.85   

   Color_intensity   Hue  OD280  Proline  
0             5.64  1.04   3.92     1065  
1             4.38  1.05   3.40     1050  
2             5.68  1.03   3.17     1185  
3             7.80  0.86   3.45     1480  
4             4.32  1.04   2.93      735  
5             6.75  1.05   2.85     1450  
6             5.25  1.02   3.58     1290  
7             5.05  1.06   3.58     1295  
8             5.20  1.08   2.85     1045  
9             7.22  1.01   3.55     1045

In [35]:
wine_df.shape# curse of dimentionality

(178, 14)

In [36]:
wine_df['Cultivator'].value_counts()

2    71
1    59
3    48
Name: Cultivator, dtype: int64

In [37]:
14*14

196

In [38]:
#import seaborn as sns
#sns.pairplot(wine_df,diag_kind='kde')

In [39]:
wine_df.info()  # many columns are of type object i.e. strings. These need to be converted to ordinal type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Cultivator            178 non-null    int64  
 1   Alchol                178 non-null    float64
 2   Malic_Acid            178 non-null    float64
 3   Ash                   178 non-null    float64
 4   Alcalinity_of_Ash     178 non-null    float64
 5   Magnesium             178 non-null    int64  
 6   Total_phenols         178 non-null    float64
 7   Falvanoids            178 non-null    float64
 8   Nonflavanoid_phenols  178 non-null    float64
 9   Proanthocyanins       178 non-null    float64
 10  Color_intensity       178 non-null    float64
 11  Hue                   178 non-null    float64
 12  OD280                 178 non-null    float64
 13  Proline               178 non-null    int64  
dtypes: float64(11), int64(3)
memory usage: 19.6 KB


In [40]:
# splitting data into training and test set for independent attributes
from sklearn.model_selection import train_test_split

X =  wine_df.drop("Cultivator", axis=1)
y =  wine_df.pop("Cultivator")

train_set, test_set, train_labels, test_labels = train_test_split(X, y, test_size=0.30, random_state=2)





In [41]:
X.head()

Alchol  Malic_Acid   Ash  Alcalinity_of_Ash  Magnesium  Total_phenols  \
0   14.23        1.71  2.43               15.6        127           2.80   
1   13.20        1.78  2.14               11.2        100           2.65   
2   13.16        2.36  2.67               18.6        101           2.80   
3   14.37        1.95  2.50               16.8        113           3.85   
4   13.24        2.59  2.87               21.0        118           2.80   

   Falvanoids  Nonflavanoid_phenols  Proanthocyanins  Color_intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280  Proline  
0   3.92     1065  
1   3.40     1050  
2   3.17     1185  
3   3.45     1480  
4   2.93      735

In [42]:
X.tail()

Alchol  Malic_Acid   Ash  Alcalinity_of_Ash  Magnesium  Total_phenols  \
173   13.71        5.65  2.45               20.5         95           1.68   
174   13.40        3.91  2.48               23.0        102           1.80   
175   13.27        4.28  2.26               20.0        120           1.59   
176   13.17        2.59  2.37               20.0        120           1.65   
177   14.13        4.10  2.74               24.5         96           2.05   

     Falvanoids  Nonflavanoid_phenols  Proanthocyanins  Color_intensity   Hue  \
173        0.61                  0.52             1.06              7.7  0.64   
174        0.75                  0.43             1.41              7.3  0.70   
175        0.69                  0.43             1.35             10.2  0.59   
176        0.68                  0.53             1.46              9.3  0.60   
177        0.76                  0.56             1.35              9.2  0.61   

     OD280  Proline  
173   1.74      740  
174   1.56      750  
175   1.56      835  
176   1.62      840  
177   1.60      560

In [43]:
# invoking the decision tree classifier function. Using 'entropy' method of finding the split columns. Other option 
# could be gini index.  Restricting the depth of the tree to 5 (no particular reason for selecting this)

#dt_model = DecisionTreeClassifier(criterion = 'entropy' , max_depth = 5, random_state = 100)
                                  
dt_model = DecisionTreeClassifier(criterion = 'gini' ,random_state=0,max_depth=4)

In [44]:
dt_model.fit(train_set, train_labels)

DecisionTreeClassifier(max_depth=4, random_state=0)

In [45]:
y_pred=dt_model.predict(test_set)   # performance on test data
acc=metrics.accuracy_score(test_labels,y_pred)
print(acc)

0.9074074074074074


In [46]:
cm=metrics.confusion_matrix(test_labels,y_pred)
print(cm)

[[18  2  0]
 [ 0 20  0]
 [ 0  3 11]]


In [47]:
cr=metrics.classification_report(test_labels,y_pred)
print(cr)

              precision    recall  f1-score   support

           1       1.00      0.90      0.95        20
           2       0.80      1.00      0.89        20
           3       1.00      0.79      0.88        14

    accuracy                           0.91        54
   macro avg       0.93      0.90      0.91        54
weighted avg       0.93      0.91      0.91        54



In [48]:
#Perform Grid Search Method to find the optimal max_depth size
from sklearn.model_selection import GridSearchCV
parameter={'max_depth':np.arange(1,10)}
GS=GridSearchCV(dt_model,parameter,cv=3)
GS.fit(X,y)


GridSearchCV(cv=3,
             estimator=DecisionTreeClassifier(max_depth=4, random_state=0),
             param_grid={'max_depth': array([1, 2, 3, 4, 5, 6, 7, 8, 9])})

In [49]:
GS.best_params_

{'max_depth': 3}

In [50]:
from IPython.display import Image  
#import pydotplus as pydot
from sklearn import tree
from os import system

train_char_label = ['1', '2', '3']
wine_Tree_File = open('wine_tree.dot','w')
dot_data = tree.export_graphviz(dt_model, out_file=wine_Tree_File, feature_names = list(train_set), class_names = list(train_char_label))

wine_Tree_File.close()


# importance of features in the tree building ( The importance of a feature is computed as the 
#(normalized) total reduction of the criterion brought by that feature. It is also known as the Gini importance )

print (pd.DataFrame(dt_model.feature_importances_, columns = ["Imp"], index = train_set.columns))


                           Imp
Alchol                0.000000
Malic_Acid            0.022103
Ash                   0.000000
Alcalinity_of_Ash     0.000000
Magnesium             0.000000
Total_phenols         0.000000
Falvanoids            0.404575
Nonflavanoid_phenols  0.000000
Proanthocyanins       0.000000
Color_intensity       0.370751
Hue                   0.000000
OD280                 0.000000
Proline               0.202571


#                                      Regularising the Decision Tree

In [51]:
dt_model = DecisionTreeClassifier(criterion = 'gini', max_depth = 3)
dt_model.fit(train_set, train_labels)

DecisionTreeClassifier(max_depth=3)

In [52]:
wine_tree_regularized = open('wine_tree_regularized.dot','w')
dot_data = tree.export_graphviz(dt_model, out_file= wine_tree_regularized , feature_names = list(train_set), class_names = list(train_char_label))

wine_tree_regularized.close()

print (pd.DataFrame(dt_model.feature_importances_, columns = ["Imp"], index = train_set.columns))


                           Imp
Alchol                0.000000
Malic_Acid            0.000000
Ash                   0.000000
Alcalinity_of_Ash     0.000000
Magnesium             0.000000
Total_phenols         0.000000
Falvanoids            0.413719
Nonflavanoid_phenols  0.000000
Proanthocyanins       0.000000
Color_intensity       0.379131
Hue                   0.000000
OD280                 0.000000
Proline               0.207149


In [53]:
test_pred = dt_model.predict(test_set)

In [54]:
dt_model.score(test_set , test_labels)

0.9074074074074074

In [55]:
from sklearn import metrics
cr=metrics.classification_report(test_pred , test_labels)
print(cr)

              precision    recall  f1-score   support

           1       0.90      1.00      0.95        18
           2       1.00      0.80      0.89        25
           3       0.79      1.00      0.88        11

    accuracy                           0.91        54
   macro avg       0.90      0.93      0.91        54
weighted avg       0.92      0.91      0.91        54

